from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, Image, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.graphics.shapes import Drawing, Rect, String
import os


def _load_personalization():
    base = "personalize_pdf"

    logo_path = None
    sign_path = None
    name = None

    if os.path.exists(base):

        # logo
        for ext in ["png", "jpg", "jpeg"]:
            p = os.path.join(base, f"logo.{ext}")
            if os.path.exists(p):
                logo_path = p
                break

        # signature
        for ext in ["png", "jpg", "jpeg"]:
            p = os.path.join(base, f"sign.{ext}")
            if os.path.exists(p):
                sign_path = p
                break

        # name
        name_file = os.path.join(base, "name.txt")
        if os.path.exists(name_file):
            with open(name_file, "r", encoding="utf-8") as f:
                name = f.read().strip()

    return logo_path, sign_path, name


def _cover_page(canvas, doc):
    canvas.saveState()
    width, height = A4

    logo_path, sign_path, name = _load_personalization()

    # Fond blanc
    canvas.setFillColor(colors.white)
    canvas.rect(0, 0, width, height, fill=1)

    canvas.setFillColor(colors.black)

    # ---- LOGO (descendu) ----
    if logo_path:
        try:
            canvas.drawImage(
                logo_path,
                width/2 - 2.5*cm,
                height - 12*cm,   # ← descendu
                width=5*cm,
                preserveAspectRatio=True,
                mask='auto'
            )
        except:
            pass

    # ---- TITRE (descendu) ----
    canvas.setFont("Helvetica-Bold", 26)
    canvas.drawCentredString(width/2, height - 16*cm, "Reconnaissance & Security Audit")

    canvas.setFont("Helvetica", 14)
    canvas.drawCentredString(width/2, height - 17.2*cm, "Confidential Security Assessment Report")

    # Nom personnalisé
    if name:
        canvas.setFont("Helvetica-Oblique", 12)
        canvas.drawCentredString(width/2, height - 18.2*cm, f"Prepared by {name}")

    # Bas de page cover
    canvas.setFont("Helvetica", 10)
    canvas.drawCentredString(width/2, 2*cm, "Generated by AutoRecon Framework")

    canvas.restoreState()


def _page_footer(canvas, doc):
    canvas.saveState()
    width, height = A4

    logo_path, sign_path, name = _load_personalization()

    footer_y = 1.2 * cm
    line_y = 1.8 * cm

    # Ligne séparation
    canvas.setStrokeColor(colors.lightgrey)
    canvas.setLineWidth(0.5)
    canvas.line(2*cm, line_y, width - 2*cm, line_y)

    # Nom gauche
    if name:
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.grey)
        canvas.drawString(2*cm, footer_y, name)

    # Logo centré (plus petit)
    if logo_path:
        try:
            logo_w = 0.9 * cm
            logo_h = 0.9 * cm
            canvas.drawImage(
                logo_path,
                (width/2) - (logo_w/2),
                footer_y - 0.5*cm,
                width=logo_w,
                height=logo_h,
                preserveAspectRatio=True,
                mask='auto'
            )
        except:
            pass

    # Pagination droite
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)
    canvas.drawRightString(width - 2*cm, footer_y, f"Page {canvas.getPageNumber()}")

    canvas.restoreState()


def _risk_color(level: str):
    level = (level or "").upper()
    if level == "HIGH":
        return "red"
    if level == "MEDIUM":
        return "orange"
    if level == "POTENTIAL":
        return "purple"
    return "green"


def _is_sensitive_port(port):
    sensitive = {21,22,23,25,3306,3389,5432,5900,6379,27017}
    try:
        return int(port) in sensitive
    except:
        return False


def _draw_ports_chart(open_ports):
    if not open_ports:
        return None

    drawing = Drawing(16*cm, 5*cm)

    max_ports_display = min(len(open_ports), 10)
    bar_width = 12*cm
    bar_height = 0.6*cm
    spacing = 0.8*cm
    height = max_ports_display * spacing + 1*cm
    drawing = Drawing(16*cm, height)

    for i, p in enumerate(open_ports[:max_ports_display]):
        port = str(p.get("port", ""))
        service = str(p.get("service", ""))

        y = height - (i + 1) * spacing

        if _is_sensitive_port(port):
            color = colors.red
        else:
            color = colors.green

        drawing.add(Rect(2*cm, y, bar_width, bar_height, fillColor=color))
        drawing.add(String(2.2*cm, y + 0.15*cm, f"{port} ({service})", fillColor=colors.white))

    return drawing


def _generate_fix_recommendation(cve):
    summary = (cve.get("summary") or "").lower()
    severity = (cve.get("cvss", {}) or {}).get("severity", "")
    cve_id = cve.get("id", "")

    fixes = []

    fixes.append("• Update the affected software to the latest stable version.")
    fixes.append("• Apply official vendor security patches.")
    fixes.append("• Restrict external access to the vulnerable service if possible.")
    fixes.append("• Implement firewall rules and intrusion detection monitoring.")

    if "remote code execution" in summary:
        fixes.append("• Immediately patch the service (RCE vulnerability detected).")
        fixes.append("• Consider temporarily disabling the affected feature.")

    if "denial of service" in summary:
        fixes.append("• Implement rate limiting and service hardening.")
        fixes.append("• Monitor abnormal traffic patterns.")

    if "authentication bypass" in summary:
        fixes.append("• Review authentication configuration.")
        fixes.append("• Enforce strong password policies and MFA if possible.")

    if severity == "CRITICAL":
        fixes.append("• PRIORITY: Treat this as a critical vulnerability.")

    return fixes


def write_pdf(report: dict, pdf_path: str):
    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        rightMargin=2*cm,
        leftMargin=2*cm,
        topMargin=2*cm,
        bottomMargin=2.7*cm
    )
    elements = []
    elements.append(Spacer(1, 1))
    elements.append(PageBreak())
    styles = getSampleStyleSheet()

    # Style Code
    if "Code" not in styles:
        styles.add(ParagraphStyle(
            name="Code",
            fontName="Courier",
            fontSize=8,
            leading=10
        ))

    # ---------- EXECUTIVE SUMMARY (Page 1) ----------
    target = report.get("input_target") or report.get("target") or "N/A"
    gen = report.get("generated_at") or "N/A"
    subs = report.get("subdomains", {}) or {}

    # stats globales
    total_subs = len(subs)
    total_pages = sum(len((d.get("pages") or [])) for d in subs.values())
    total_login_forms = sum(len((d.get("login_forms") or [])) for d in subs.values())

    # ports / cves / risk
    total_open_ports = 0
    critical_cves = 0
    high_cves = 0
    max_cvss = 0.0

    risks = []
    for d in subs.values():
        nmap_s = d.get("nmap_structured", {}) or {}
        total_open_ports += len(nmap_s.get("open_ports", []) or [])

        for v in (d.get("cves") or []):
            cvss = (v.get("cvss") or {})
            try:
                s = float(cvss.get("score"))
                max_cvss = max(max_cvss, s)
                if s >= 9.0:
                    critical_cves += 1
                elif s >= 7.0:
                    high_cves += 1
            except Exception:
                pass

        r = d.get("risk") or {}
        if r.get("score") is not None:
            risks.append(r["score"])

    worst_risk = max(risks) if risks else 0
    avg_risk = round(sum(risks) / len(risks), 1) if risks else 0
    overall_level = "LOW" if worst_risk < 25 else "MEDIUM" if worst_risk < 60 else "HIGH"
    overall_color = _risk_color(overall_level)

    elements.append(Paragraph("<b>Recon Audit Report</b>", styles["Title"]))
    elements.append(Spacer(1, 10))
    elements.append(Paragraph(f"Target: <b>{target}</b>", styles["Normal"]))
    elements.append(Paragraph(f"Generated: {gen}", styles["Normal"]))
    elements.append(Spacer(1, 12))

    elements.append(Paragraph("<b>Executive Summary</b>", styles["Heading2"]))
    elements.append(Spacer(1, 8))

    summary_table = Table([
        ["Overall Risk", Paragraph(
            f"<font color='{overall_color}'><b>{overall_level}</b></font> "
            f"(worst={worst_risk}, avg={avg_risk})",
            styles["Normal"]
        )],
        ["Subdomains / Targets analyzed", str(total_subs)],
        ["Total open ports (sum)", str(total_open_ports)],
        ["Pages discovered", str(total_pages)],
        ["Login forms detected", str(total_login_forms)],
        ["CVE High / Critical", f"{high_cves} / {critical_cves} (max CVSS={max_cvss})"],
    ], colWidths=[7*cm, 9*cm])

    summary_table.setStyle(TableStyle([
        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
        ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
        ("FONTNAME", (0,0), (-1,-1), "Helvetica"),
        ("FONTSIZE", (0,0), (-1,-1), 10),
    ]))
    elements.append(summary_table)
    elements.append(Spacer(1, 10))

    elements.append(Paragraph(
        f"Overall risk classification is "
        f"<font color='{overall_color}'><b>{overall_level}</b></font> "
        f"based on exposed services, TLS state, and CVE severity.",
        styles["Normal"]
    ))

    elements.append(PageBreak())

    # ---------- PER SUBDOMAIN DETAILS ----------
    for sub, data in subs.items():
        elements.append(Paragraph(f"<b>Target: {sub}</b>", styles["Heading2"]))
        elements.append(Spacer(1, 6))

        # Risk score (coloré)
        risk = data.get("risk") or {}
        level = (risk.get("level") or "LOW").upper()
        score = risk.get("score")
        color = _risk_color(level)
        
        if level == "HIGH":
            alert_table = Table(
                [[Paragraph(f"<b>⚠ CRITICAL RISK DETECTED ({score})</b>", styles["Normal"])]],
                colWidths=[16*cm]
            )
            alert_table.setStyle(TableStyle([
                ("BACKGROUND", (0,0), (-1,-1), colors.red),
                ("TEXTCOLOR", (0,0), (-1,-1), colors.white),
                ("ALIGN", (0,0), (-1,-1), "CENTER"),
                ("FONTSIZE", (0,0), (-1,-1), 12),
            ]))
            elements.append(alert_table)
            elements.append(Spacer(1, 8))

        elements.append(Paragraph(
            f"Risk: <font color='{color}'><b>{level}</b></font>"
            + (f" (score={score})" if score is not None else ""),
            styles["Normal"]
        ))

        reasons = risk.get("reasons") or []
        if reasons:
            for r in reasons[:8]:
                elements.append(Paragraph(f"- {r}", styles["Normal"]))
        elements.append(Spacer(1, 10))

        # --- Ports ouverts (table structurée) ---
        nmap_s = data.get("nmap_structured", {}) or {}
        open_ports = nmap_s.get("open_ports", []) or []
        ip = nmap_s.get("ip")
        rdns = nmap_s.get("rdns")

        if ip or rdns:
            elements.append(Paragraph("<b>Nmap Host Info</b>", styles["Heading3"]))
            if ip:
                elements.append(Paragraph(f"IP: {ip}", styles["Normal"]))
            if rdns and rdns != sub:
                elements.append(Paragraph(f"rDNS: {rdns}", styles["Normal"]))
            elements.append(Spacer(1, 6))

        # --- Infrastructure / Geolocation ---
        ip_enrichment = data.get("ip_enrichment", []) or []

        for ip_info in ip_enrichment:
            geo = ip_info.get("geo") or {}
            rdap = ip_info.get("rdap") or {}

            elements.append(Paragraph("<b>Infrastructure Information</b>", styles["Heading3"]))

            infra_table = [
                ["IP", ip_info.get("ip")],
                ["Reverse DNS", ip_info.get("reverse_dns")],
                ["Country", geo.get("country")],
                ["Region", geo.get("region")],
                ["City", geo.get("city")],
                ["ISP", geo.get("isp")],
                ["ASN", geo.get("as")],
                ["Network Range", f"{rdap.get('startAddress')} - {rdap.get('endAddress')}"],
                ["Network Name", rdap.get("name")]
            ]

            t = Table(infra_table, colWidths=[5 * cm, 10 * cm])
            t.setStyle(TableStyle([
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
            ]))

            elements.append(t)
            elements.append(Spacer(1, 12))

        if open_ports:
            elements.append(Paragraph("<b>Open Ports</b>", styles["Heading3"]))
            rows = [["Port", "Proto", "Service", "Product", "Version / Extra"]]
            for p in open_ports:
                port = str(p.get("port", ""))
                service = str(p.get("service", ""))

                if _is_sensitive_port(port):
                    port_cell = Paragraph(f"<font color='red'><b>{port}</b></font>", styles["Normal"])
                else:
                    port_cell = Paragraph(port, styles["Normal"])

                rows.append([
                    port_cell,
                    Paragraph(str(p.get("proto", "")), styles["Normal"]),
                    Paragraph(service, styles["Normal"]),
                    Paragraph(str(p.get("product") or ""), styles["Normal"]),
                    Paragraph(str(p.get("version_raw") or ""), styles["Normal"])
                ])

            t = Table(rows, colWidths=[2*cm, 2*cm, 3*cm, 4*cm, 5*cm])
            t.setStyle(TableStyle([
                ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
                ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
                ("FONTSIZE", (0,0), (-1,-1), 8),
                ("WORDWRAP", (0,0), (-1,-1), "CJK"),
                ("VALIGN", (0,0), (-1,-1), "TOP"),
            ]))
            elements.append(t)
            elements.append(Spacer(1, 12))

            # Diagramme des ports
            chart = _draw_ports_chart(open_ports)
            if chart:
                elements.append(Spacer(1, 8))
                elements.append(Paragraph("<b>Open Ports Overview</b>", styles["Heading3"]))
                elements.append(Spacer(1, 6))
                elements.append(KeepTogether(chart))
                elements.append(Spacer(1, 12))
        else:
            # fallback: affiche brut si pas structuré
            nmap_raw = data.get("nmap_raw")
            if nmap_raw:
                elements.append(Paragraph("<b>Nmap Results (raw)</b>", styles["Heading3"]))
                for line in nmap_raw.split("\n"):
                    if line.strip():
                        elements.append(Paragraph(line.replace("&", "&amp;"), styles["Code"]))
                elements.append(Spacer(1, 12))

        # TLS
        tls = data.get("tls", {}) or {}
        if tls:
            elements.append(Paragraph("<b>TLS Information</b>", styles["Heading3"]))
            elements.append(Spacer(1, 6))

            # Cipher propre
            cipher = tls.get("cipher")
            if isinstance(cipher, (list, tuple)) and len(cipher) >= 1:
                cipher_display = f"{cipher[0]} ({cipher[1] if len(cipher)>1 else ''})"
            else:
                cipher_display = str(cipher)

            # Issuer propre
            issuer = tls.get("cert_issuer")
            issuer_display = ""
            if isinstance(issuer, list):
                parts = []
                for item in issuer:
                    try:
                        key, value = item[0]
                        parts.append(f"{key}={value}")
                    except Exception:
                        pass
                issuer_display = "<br/>".join(parts)
            else:
                issuer_display = str(issuer)

            tls_data = [
                ["Protocol", Paragraph(str(tls.get("protocol")), styles["Normal"])],
                ["Cipher", Paragraph(cipher_display, styles["Normal"])],
                ["Issuer", Paragraph(issuer_display, styles["Normal"])],
                ["Valid From", Paragraph(str(tls.get("not_before")), styles["Normal"])],
                ["Valid Until", Paragraph(str(tls.get("not_after")), styles["Normal"])],
                ["Expired", Paragraph(str(tls.get("cert_expired")), styles["Normal"])],
            ]

            t = Table(tls_data, colWidths=[4*cm, 12*cm], repeatRows=0)

            t.setStyle(TableStyle([
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ]))

            elements.append(t)
            elements.append(Spacer(1, 12))

        # CMS/WAF
        # ===== DETECTED TECHNOLOGIES (HTTP + NMAP) =====
        technologies = set()

        # 1️⃣ Technologies HTTP / CMS
        for tech in data.get("cms", []) or []:
            name = tech.lower().strip()

            # Nettoyage "Server: nginx"
            if ":" in name:
                name = name.split(":", 1)[1].strip()

            technologies.add(name)

        # MASSCAN RESULTS
        masscan_data = data.get("masscan", {})
        masscan_ports = []

        for ip in masscan_data:
            masscan_ports.extend(masscan_data[ip])

        if masscan_ports:
            elements.append(Paragraph("<b>Masscan Fast Port Discovery</b>", styles["Heading3"]))

            elements.append(Paragraph(
                f"Masscan detected <b>{len(masscan_ports)}</b> open ports during high-speed scan.",
                styles["Normal"]
            ))

            port_list = ", ".join(str(p) for p in sorted(set(masscan_ports))[:30])

            elements.append(Paragraph(f"Ports: {port_list}", styles["Code"]))
            elements.append(Spacer(1,10))

        # 2️⃣ Services Nmap
        nmap_s = data.get("nmap_structured", {}) or {}
        open_ports = nmap_s.get("open_ports", []) or []

        for p in open_ports:
            product = p.get("product")
            if product:
                name = product.lower().strip()
                technologies.add(name)

        # 🔎 Affichage
        if technologies:
            elements.append(Paragraph("<b>Detected Technologies</b>", styles["Heading3"]))

            for tech in sorted(technologies):
                elements.append(Paragraph(f"- {tech.title()}", styles["Normal"]))

            elements.append(Spacer(1, 8))

        waf = data.get("waf", []) or []
        if waf:
            elements.append(Paragraph("<b>WAF Detection</b>", styles["Heading3"]))
            for w in waf:
                elements.append(Paragraph(f"- {w}", styles["Normal"]))
            elements.append(Spacer(1, 8))

        # HTTPX WEB SERVICE DETECTION
        httpx_results = data.get("httpx", []) or []

        if httpx_results:
            elements.append(Paragraph("<b>HTTP Services Detected (HTTPX)</b>", styles["Heading3"]))

            rows = [["URL", "Status", "Title", "Technology", "Web Server"]]

            for r in httpx_results[:15]:
                rows.append([
                    Paragraph(str(r.get("url")), styles["Normal"]),
                    Paragraph(str(r.get("status_code")), styles["Normal"]),
                    Paragraph(str(r.get("title") or ""), styles["Normal"]),
                    Paragraph(str(r.get("tech") or ""), styles["Normal"]),
                    Paragraph(str(r.get("webserver") or ""), styles["Normal"])
                ])

            table = Table(rows, colWidths=[7*cm, 2*cm, 4*cm, 3*cm])
            table.setStyle(TableStyle([
                ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
                ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
                ("FONTSIZE", (0,0), (-1,-1), 8),
            ]))

            elements.append(table)
            elements.append(Spacer(1, 10))

        # Pages
        pages = data.get("pages", []) or []
        if pages:
            elements.append(Paragraph("<b>Web Discovery</b>", styles["Heading3"]))
            elements.append(Paragraph(f"Total pages discovered: {len(pages)}", styles["Normal"]))
            restricted = [p for p in pages if p.get("status") == 403]
            elements.append(Paragraph(f"Restricted resources (403): {len(restricted)}", styles["Normal"]))
            elements.append(Spacer(1, 8))

        # NUCLEI SCAN RESULTS
        nuclei = data.get("nuclei", []) or []

        if nuclei:
            elements.append(Paragraph("<b>Nuclei Vulnerability Scan</b>", styles["Heading3"]))
            elements.append(Spacer(1,6))

            rows = [["Template", "Severity", "Matched URL", "Description"]]

            for v in nuclei[:20]:
                sev = v.get("severity","").upper()

                if sev == "CRITICAL":
                    color = "red"
                elif sev == "HIGH":
                    color = "orange"
                elif sev == "MEDIUM":
                    color = "purple"
                else:
                    color = "green"

                rows.append([
                    Paragraph(str(v.get("template")), styles["Normal"]),
                    Paragraph(f"<font color='{color}'>{sev}</font>", styles["Normal"]),
                    Paragraph(str(v.get("url")), styles["Code"]),
                    Paragraph(str(v.get("info", {}).get("name","")), styles["Normal"])
                ])

            t = Table(rows, colWidths=[6*cm, 3*cm, 7*cm])

            t.setStyle(TableStyle([
                ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
                ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
                ("FONTSIZE", (0,0), (-1,-1), 8),
            ]))

            elements.append(t)
            elements.append(Spacer(1,12))

        # CVEs
        cves = data.get("cves", []) or []
        if cves:
            elements.append(Paragraph("<b>Identified CVEs</b>", styles["Heading3"]))
            elements.append(Spacer(1, 6))
            for v in cves[:12]:
                cvss = v.get("cvss", {}) or {}
                score_txt = cvss.get("score")
                sev = cvss.get("severity")
                risk_data = data.get("risk", {})
                version_unknown = risk_data.get("version_unknown", False)

                try:
                    score_val = float(score_txt)
                except:
                    score_val = 0

                original_sev = sev

                # Déterminer la couleur réelle du severity
                if score_val >= 9:
                    real_color = "red"
                elif score_val >= 7:
                    real_color = "orange"
                else:
                    real_color = "black"

                if version_unknown:
                    badge = "⚠ "
                    color = "purple"

                    sev_display = (
                        "POTENTIAL – original: "
                        f"<font color='{real_color}'>{original_sev}</font>"
                    )
                else:
                    badge = ""
                    color = real_color
                    sev_display = original_sev

                cve_id = v.get("id")
                nvd_url = f"https://nvd.nist.gov/vuln/detail/{cve_id}"

                elements.append(Paragraph(
                    f"<b>{badge}<a href='{nvd_url}' color='blue'><u>{cve_id}</u></a></b> | "
                    f"<font color='{color}'>CVSS: {score_txt} ({sev_display})</font>",
                    styles["Normal"]
                ))

                if v.get("summary"):
                    elements.append(Paragraph(v.get("summary"), styles["Normal"]))

                # Explication automatique si version inconnue
                if version_unknown:
                    elements.append(Paragraph(
                        "<font color='purple'><i>"
                        "Version not disclosed by server — impact cannot be confirmed."
                        "</i></font>",
                        styles["Normal"]
                    ))

                elements.append(Spacer(1, 6))

                # # --- HOW TO FIX SECTION ---
                # elements.append(Paragraph(
                #     "<b>How to fix this vulnerability:</b>",
                #     ParagraphStyle(
                #         'FixStyle',
                #         parent=styles['Normal'],
                #         textColor=colors.darkblue
                #     )
                # ))
                # elements.append(Spacer(1, 2))

                # fixes = _generate_fix_recommendation(v)

                # for fix in fixes:
                #     elements.append(Paragraph(fix, styles["Normal"]))

                # elements.append(Spacer(1, 10))

        if sub != list(subs.keys())[-1]:
            elements.append(PageBreak())

    # ---------- SIGNATURE PAGE ----------
    logo_path, sign_path, name = _load_personalization()

    if name:
        elements.append(PageBreak())
        elements.append(Paragraph("<b>Author</b>", styles["Heading2"]))
        elements.append(Spacer(1, 6))

        elements.append(Paragraph(
            f"Analysis report prepared by <b>{name}</b>.",
            styles["Normal"]
        ))
        elements.append(Spacer(1, 20))

        if sign_path:
            try:
                sign_img = Image(sign_path, width=5*cm, height=2*cm)
                elements.append(sign_img)
            except:
                pass

    doc.build(elements, onFirstPage=_cover_page, onLaterPages=_page_footer)
